package com.imooc.li.car.dao;

import com.imooc.li.car.data.AdminDO;
import org.apache.ibatis.annotations.Param;

/**
 * @author LI
 */
public interface AdminDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    int insert(@Param("record") AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    int insertSelective(@Param("record") AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    AdminDO selectByPrimaryKey(@Param("id") Integer id);

    AdminDO login(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    int updateByPrimaryKeySelective(@Param("record") AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    int updateByPrimaryKey(@Param("record") AdminDO record);

    int update(@Param("adminDO") AdminDO adminDO);
}