package com.imooc.li.car.dao;

import com.imooc.li.car.data.CarDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByID(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    int insert(CarDo record);

    List<CarDo> selectALL();

    List<CarDo> selectByUserName(String name);

    List<CarDo> selectByUserID(Integer id);

    List<CarDo> queryAllByLimit(@Param("offset") int offset, @Param("limit") int limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    int insertSelective(CarDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    CarDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    int updateByPrimaryKeySelective(CarDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CarDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Fri Mar 06 12:48:48 CST 2020
     */
    int updateByPrimaryKey(CarDo record);
}