package com.imooc.li.car.dao;

import com.imooc.li.car.data.UserDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Dec 11 11:46:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Dec 11 11:46:56 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Dec 11 11:46:56 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Dec 11 11:46:56 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);

    UserDO selectByName(String name);

    List<UserDO> selectALL();

    List<UserDO> selectByUserName(String name);

    List<UserDO> queryAllByLimit(@Param("offset") int offset, @Param("limit") int limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Dec 11 11:46:56 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Dec 11 11:46:56 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}