package com.imooc.li.car.dao;

import com.imooc.li.car.data.WordDo;

import java.util.List;

public interface WordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByID(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    int insert(WordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    int insertSelective(WordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    WordDo selectByPrimaryKey(Integer id);

    List<WordDo> selectByUserName(String name);

    List<WordDo> selectByQuestionID(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    int updateByPrimaryKeySelective(WordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    int updateByPrimaryKey(WordDo record);
}