package com.imooc.li.car.data;

/**
 * @author LI
 */
public class AdminDO {
    @Override
    public String toString() {
        return "AdminDO{" +
                "id=" + id +
                ", adminName='" + adminName + '\'' +
                ", adminPassword='" + adminPassword + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ID
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_password
     *
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    private String adminPassword;

    public AdminDO(String adminName, String adminPassword) {
        this.adminName = adminName;
        this.adminPassword = adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ID
     *
     * @return the value of admin.ID
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ID
     *
     * @param id the value for admin.ID
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_password
     *
     * @return the value of admin.admin_password
     * @mbg.generated Thu Mar 05 16:01:45 CST 2020
     */
    public String getAdminPassword() {
        return adminPassword;
    }

}