package com.imooc.li.car.data;

import java.util.Date;

/**
 * @author LI
 */
public class CarDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.ID
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.username
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.name
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.power
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.price
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.date
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.description
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.vehicle
     *
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    private String vehicle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.ID
     *
     * @return the value of car.ID
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.ID
     *
     * @param id the value for car.ID
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.username
     *
     * @return the value of car.username
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.username
     *
     * @param username the value for car.username
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.name
     *
     * @return the value of car.name
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.name
     *
     * @param name the value for car.name
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.power
     *
     * @return the value of car.power
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.power
     *
     * @param power the value for car.power
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.price
     *
     * @return the value of car.price
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.price
     *
     * @param price the value for car.price
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.date
     *
     * @return the value of car.date
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.date
     *
     * @param date the value for car.date
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.description
     *
     * @return the value of car.description
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.description
     *
     * @param description the value for car.description
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.vehicle
     *
     * @return the value of car.vehicle
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.vehicle
     *
     * @param vehicle the value for car.vehicle
     * @mbg.generated Wed Mar 11 15:03:10 CST 2020
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }
}