package com.imooc.li.car.data;

/**
 * @author LI
 */
public class WordDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.ID
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.message
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.username
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.questionID
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.problem
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.progress
     *
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    private String progress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.ID
     *
     * @return the value of word.ID
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.ID
     *
     * @param id the value for word.ID
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.message
     *
     * @return the value of word.message
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.message
     *
     * @param message the value for word.message
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.username
     *
     * @return the value of word.username
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.username
     *
     * @param username the value for word.username
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.questionID
     *
     * @return the value of word.questionID
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.questionID
     *
     * @param questionid the value for word.questionID
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.problem
     *
     * @return the value of word.problem
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.problem
     *
     * @param problem the value for word.problem
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.progress
     *
     * @return the value of word.progress
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.progress
     *
     * @param progress the value for word.progress
     * @mbg.generated Tue Mar 24 10:36:05 CST 2020
     */
    public void setProgress(String progress) {
        this.progress = progress == null ? null : progress.trim();
    }
}